scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: prometheus
          partof: monitoring

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['localhost:9115']
        labels:
          service: blackbox
          partof: monitoring
